# Generated by Django 2.0.1 on 2018-01-27 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('name', models.CharField(max_length=20)),
                ('examnee', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('ques_text', models.CharField(max_length=50)),
                ('choice_1', models.CharField(max_length=20)),
                ('choice_2', models.CharField(max_length=20)),
                ('choice_3', models.CharField(max_length=20)),
                ('choice_4', models.CharField(max_length=20)),
                ('exam_name', models.ManyToManyField(blank=True, to='exams.Exam')),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('response_field', models.CharField(blank=True, max_length=20, null=True)),
                ('exam_fkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_rel', related_query_name='exam_rel_q', to='exams.Exam')),
                ('question_fkey', models.ForeignKey(blank=True, default='A', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ques_rel', related_query_name='ques_rel_q', to='exams.Question')),
            ],
            bases=('users.base',),
        ),
    ]
