# Generated by Django 2.0.1 on 2018-01-27 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20180127_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='question_fkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ques_rel', related_query_name='ques_rel_q', to='exams.Question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
